# Generated by Django 5.2.7 on 2025-11-03 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_result_end_time_result_finished_test_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='true_tests', to='api.variant'),
        ),
    ]
