# Generated by Django 5.2.7 on 2025-11-03 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_test_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_image', to='api.test'),
        ),
    ]
